### ISSUE TITLE
"Godot" is damaged and can't be opened

### ISSUE THREAD

**Issue by djrain** [goostengine/goost#94]
**Goost and Godot version:**
Godot 3.3.2-stable + Goost 1.0-stable

**OS/platform/device including version:**
2020 Mac Mini (M1)
macOS Big Sur

**Issue description:**
Downloaded Godot + Goost (macOS standard 64-bit) for the first time, but when I unzip and try to open it, I get this:

<img width="285" alt="Screen Shot 2021-06-26 at 2 19 21 PM" src="https://user-images.githubusercontent.com/33777501/123526293-c17e2500-d68b-11eb-9ff3-52c0376f0c72.png">

No idea what would cause this... I am running the official 3.3.2 stable just fine. 
I tried redownloading it and also restarting to no avail. Anyone else encountered this?

**Steps to reproduce:**
dunno... try to open Godot + Goost on M1 Mac?

**Is this issue reproducible in official Godot builds?**
no

**Minimal reproduction project:**
N/A

**Comment by Xrayez** [comment]
Ok, thanks for reporting, looks like there may be extra steps that are needed to make those work. Unfortunately, I don't currently have access to Mac machine to properly test this myself and figure out what could be the cause of this, all the binaries were built using official Godot build containers and scripts.

If someone has any ideas and expertise in this, I'd appreciate any feedback.

If this issue still persists in future builds, I think it would be worth to link this issue in a "Known issues" on the Goost's Download page, but those should be fixed of course.

If you're familiar with the process of compiling from source, you may still be able to use Goost.

**Comment by Xrayez** [comment]
This may likely be due to verification process. Official *Godot* binaries, as far as I know, are currently notarized/code-signed. There may be ways to workaround this as well.

Perhaps doing hacks like https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t may also workaround the issue.

**Comment by djrain** [comment]
> Perhaps doing hacks like https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t may also workaround the issue.

I've just tried running that command:
`sudo xattr -rds com.apple.quarantine /Applications/Godot-3.3.2-Goost.app/Contents/MacOS/Godot
`

but it didn't fix it. Also tried this to enable the "allow apps downloaded from anywhere" setting 
`sudo spctl --master-disable`

but still no luck :/ 
I also tried opening it on my 2015 Macbook running Catalina, and got the same message.

Will compile if I have to, but it would be nice to avoid it.

**Comment by Xrayez** [comment]
@djrain is the previous beta release also broken when running on your machine? See https://github.com/goostengine/goost/releases/tag/1.0-beta-gd3.

If not, this may be something more to do in the way I've updated the local buildsystem which lead to damaged binaries for real, otherwise I still suspect this is due to code signing, or lack of thereof, when I build those binaries, which isn't something which I can do at the moment. Basically see:

https://github.com/godotengine/godot/issues/11984#issuecomment-356122756

Maybe, just maybe, macOS sees custom builds of Godot as broken because they are very similar to Godot's official ones (because Godot builds are already signed and notarized). They could somehow see a mismatch between official Godot builds and Goost builds. The difference between Godot and Goost builds are literally just 1.5 Mb at the moment. 😃

**Comment by djrain** [comment]
> @djrain is the previous beta release also broken when running on your machine?

Yeah, it's broken also.

However, running this command (from thread you linked) allowed 1.0 to open without issue :)
`xattr -r -d com.apple.quarantine /Applications/Godot-3.3.2-Goost.app`

**Comment by TrueSgtMonkey** [comment]
This issue just happened to me on 3.4.4. I tried the above tips, but the .app is still being marked as damaged on macOS Big Sur.

**Comment by Xrayez** [comment]
@TrueSgtMonkey have you tried the workaround described in #143?

**Comment by TrueSgtMonkey** [comment]
> @TrueSgtMonkey have you tried the workaround described in #143?
> 

For some reason the other day it didn't work, but this time it did. Thank you!

I bet it was a user error on my part as I was exhausted that day haha
